### PR TITLE
add ZyXEL NWA55AXE, Asus TUF AX4200, Netgear WAX220, GL.iNet GL-XE300, Siemens WS-AP3610 and ZTE MF281

### PR DESCRIPTION
**Pull request by herbetom**
I've created some SVGs for a few devices.

### CODE REVIEW

**Comment by maurerle** [comment]
Could you please add the statement, that the devices are licensed by yourself
> Licensed under [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).

Additionally, it is needed for the Gl.iNet device to create the file as `gl-inet-gl-xe300.svg` (for the meshviewer which replaces dots in the filename) and a symlink to `gl.inet-gl-xe300.svg` as it is requested by the gluon-firmware-selector.

In the long term I would like to remove the need for this

**Comment by maurerle** [comment]
Sorry, am I missing the actual gl.iNet GL-XE300 file now?
In the changes it looks like only the symlink is added now?

**Comment by herbetom** [comment]
Yeah, seems like i forgot to add that file. Should be fixed now.

**Comment by maurerle** [comment]
Thank you, very much for the new pictures! :)

**Pull request merged**
